# Generated by Django 4.1.3 on 2022-11-19 18:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Name')),
                ('permissions', models.JSONField(default=account.models._default_permissions, verbose_name='Permissions')),
            ],
        ),
    ]
